export const ADD_STATISTICS = "ADD_STATISTICS"
export const ADD_FILTERED_STATISTICS = "ADD_FILTERED_STATISTICS"
export const REMOVE_FILTERED_STATISTICS = "REMOVE_FILTERED_STATISTICS"
export const SWITCH_FILTER_IN_USE = "SWITCH_FILTER_IN_USE"
